// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.82.6.
            // ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const
            
import 'dart:convert';
            import 'dart:async';
            import 'dart:typed_data';
            import 'package:meta/meta.dart';
            import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

import 'dart:ffi' as ffi;















        abstract class KeyboardApi {
            Future<List<KeyboardLayoutInfo>> supportedLayouts({ dynamic hint });

FlutterRustBridgeTaskConstMeta get kSupportedLayoutsConstMeta;

Future<String> exampleConfig({ dynamic hint });

FlutterRustBridgeTaskConstMeta get kExampleConfigConstMeta;

Future<ValidationSummary> validateConfigYaml({ required String yaml ,dynamic hint });

FlutterRustBridgeTaskConstMeta get kValidateConfigYamlConstMeta;

Future<void> uploadConfigYaml({ required String yaml ,DevelOptions? options ,dynamic hint });

FlutterRustBridgeTaskConstMeta get kUploadConfigYamlConstMeta;
        }

        













class DevelOptions  {
                    final int vendorId;
final int? productId;
final (int,int)? address;
final int? endpointAddress;
final int? interfaceNumber;

                    const DevelOptions({required this.vendorId ,this.productId ,this.address ,this.endpointAddress ,this.interfaceNumber ,});

                
            }

class KeyboardLayoutInfo  {
                    final String name;
final int rows;
final int columns;
final int knobs;
final String description;

                    const KeyboardLayoutInfo({required this.name ,required this.rows ,required this.columns ,required this.knobs ,required this.description ,});

                
            }





















class ValidationSummary  {
                    final int layers;
final int buttons;
final int knobs;

                    const ValidationSummary({required this.layers ,required this.buttons ,required this.knobs ,});

                
            }
        

class KeyboardApiImpl implements KeyboardApi {
                final KeyboardApiPlatform _platform;
                factory KeyboardApiImpl(ExternalLibrary dylib) => KeyboardApiImpl.raw(KeyboardApiPlatform(dylib));

                /// Only valid on web/WASM platforms.
                factory KeyboardApiImpl.wasm(FutureOr<WasmModule> module) =>
                    KeyboardApiImpl(module as ExternalLibrary);
                KeyboardApiImpl.raw(this._platform);
Future<List<KeyboardLayoutInfo>> supportedLayouts({ dynamic hint }) {
            
            return _platform.executeNormal(FlutterRustBridgeTask(
            callFfi: (port_) => _platform.inner.wire_supported_layouts(port_),
            parseSuccessData: _wire2api_list_keyboard_layout_info,
            parseErrorData: null,
            
        constMeta: kSupportedLayoutsConstMeta,
        argValues: [],
        hint: hint,
        
        ));}


        FlutterRustBridgeTaskConstMeta get kSupportedLayoutsConstMeta => const FlutterRustBridgeTaskConstMeta(
            debugName: "supported_layouts",
            argNames: [],
        );
        
Future<String> exampleConfig({ dynamic hint }) {
            
            return _platform.executeNormal(FlutterRustBridgeTask(
            callFfi: (port_) => _platform.inner.wire_example_config(port_),
            parseSuccessData: _wire2api_String,
            parseErrorData: null,
            
        constMeta: kExampleConfigConstMeta,
        argValues: [],
        hint: hint,
        
        ));}


        FlutterRustBridgeTaskConstMeta get kExampleConfigConstMeta => const FlutterRustBridgeTaskConstMeta(
            debugName: "example_config",
            argNames: [],
        );
        
Future<ValidationSummary> validateConfigYaml({ required String yaml ,dynamic hint }) {
            var arg0 = _platform.api2wire_String(yaml);
            return _platform.executeNormal(FlutterRustBridgeTask(
            callFfi: (port_) => _platform.inner.wire_validate_config_yaml(port_, arg0),
            parseSuccessData: _wire2api_validation_summary,
            parseErrorData: _wire2api_FrbAnyhowException,
            
        constMeta: kValidateConfigYamlConstMeta,
        argValues: [yaml],
        hint: hint,
        
        ));}


        FlutterRustBridgeTaskConstMeta get kValidateConfigYamlConstMeta => const FlutterRustBridgeTaskConstMeta(
            debugName: "validate_config_yaml",
            argNames: ["yaml"],
        );
        
Future<void> uploadConfigYaml({ required String yaml ,DevelOptions? options ,dynamic hint }) {
            var arg0 = _platform.api2wire_String(yaml);
var arg1 = _platform.api2wire_opt_box_autoadd_devel_options(options);
            return _platform.executeNormal(FlutterRustBridgeTask(
            callFfi: (port_) => _platform.inner.wire_upload_config_yaml(port_, arg0, arg1),
            parseSuccessData: _wire2api_unit,
            parseErrorData: _wire2api_FrbAnyhowException,
            
        constMeta: kUploadConfigYamlConstMeta,
        argValues: [yaml, options],
        hint: hint,
        
        ));}


        FlutterRustBridgeTaskConstMeta get kUploadConfigYamlConstMeta => const FlutterRustBridgeTaskConstMeta(
            debugName: "upload_config_yaml",
            argNames: ["yaml", "options"],
        );
        
void dispose() {_platform.dispose();}
// Section: wire2api

FrbAnyhowException _wire2api_FrbAnyhowException(dynamic raw) {
            return FrbAnyhowException(raw as String);
        }
        

String _wire2api_String(dynamic raw) {
            return raw as String;
        }
        

KeyboardLayoutInfo _wire2api_keyboard_layout_info(dynamic raw) {
            final arr = raw as List<dynamic>;
                if (arr.length != 5) throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
                return KeyboardLayoutInfo(name: _wire2api_String(arr[0]),
rows: _wire2api_u8(arr[1]),
columns: _wire2api_u8(arr[2]),
knobs: _wire2api_u8(arr[3]),
description: _wire2api_String(arr[4]),);
        }
        

List<KeyboardLayoutInfo> _wire2api_list_keyboard_layout_info(dynamic raw) {
            return (raw as List<dynamic>).map(_wire2api_keyboard_layout_info).toList();
        }
        

int _wire2api_u8(dynamic raw) {
            return raw as int;
        }
        

Uint8List _wire2api_uint_8_list(dynamic raw) {
            return raw as Uint8List;
        }
        

void _wire2api_unit(dynamic raw) {
            return;
        }
        

int _wire2api_usize(dynamic raw) {
            return castInt(raw);
        }
        

ValidationSummary _wire2api_validation_summary(dynamic raw) {
            final arr = raw as List<dynamic>;
                if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
                return ValidationSummary(layers: _wire2api_usize(arr[0]),
buttons: _wire2api_u8(arr[1]),
knobs: _wire2api_u8(arr[2]),);
        }
        
}

// Section: api2wire












@protected
                    int api2wire_u16(int raw) {
                        return raw;
                    }
@protected
                    int api2wire_u8(int raw) {
                        return raw;
                    }

// Section: finalizer




class KeyboardApiPlatform extends FlutterRustBridgeBase<KeyboardApiWire> {
                KeyboardApiPlatform(ffi.DynamicLibrary dylib) : super(KeyboardApiWire(dylib));

// Section: api2wire

@protected
                    ffi.Pointer<wire_uint_8_list> api2wire_String(String raw) {
                        return api2wire_uint_8_list(utf8.encoder.convert(raw));
                    }

@protected
                    ffi.Pointer<wire___record__u8_u8> api2wire_box_autoadd___record__u8_u8((int,int) raw) {
                        final ptr = inner.new_box_autoadd___record__u8_u8_0();
                        _api_fill_to_wire___record__u8_u8(raw, ptr.ref);
                        return ptr;
                    }
@protected
                    ffi.Pointer<wire_DevelOptions> api2wire_box_autoadd_devel_options(DevelOptions raw) {
                        final ptr = inner.new_box_autoadd_devel_options_0();
                        _api_fill_to_wire_devel_options(raw, ptr.ref);
                        return ptr;
                    }
@protected
                    ffi.Pointer<ffi.Uint16> api2wire_box_autoadd_u16(int raw) {
                        return inner.new_box_autoadd_u16_0(api2wire_u16(raw));
                    }
@protected
                    ffi.Pointer<ffi.Uint8> api2wire_box_autoadd_u8(int raw) {
                        return inner.new_box_autoadd_u8_0(api2wire_u8(raw));
                    }

@protected
                    ffi.Pointer<wire___record__u8_u8> api2wire_opt_box_autoadd___record__u8_u8((int,int)? raw) {
                        return raw == null ? ffi.nullptr : api2wire_box_autoadd___record__u8_u8(raw);
                    }
@protected
                    ffi.Pointer<wire_DevelOptions> api2wire_opt_box_autoadd_devel_options(DevelOptions? raw) {
                        return raw == null ? ffi.nullptr : api2wire_box_autoadd_devel_options(raw);
                    }
@protected
                    ffi.Pointer<ffi.Uint16> api2wire_opt_box_autoadd_u16(int? raw) {
                        return raw == null ? ffi.nullptr : api2wire_box_autoadd_u16(raw);
                    }
@protected
                    ffi.Pointer<ffi.Uint8> api2wire_opt_box_autoadd_u8(int? raw) {
                        return raw == null ? ffi.nullptr : api2wire_box_autoadd_u8(raw);
                    }


@protected
                    ffi.Pointer<wire_uint_8_list> api2wire_uint_8_list(Uint8List raw) {
                        final ans = inner.new_uint_8_list_0(raw.length);
                ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
                return ans;
                    }
// Section: finalizer


// Section: api_fill_to_wire



void _api_fill_to_wire___record__u8_u8((int,int) apiObj, wire___record__u8_u8 wireObj) {
                wireObj.field0 = api2wire_u8(apiObj.$1);
wireObj.field1 = api2wire_u8(apiObj.$2);
            }

void _api_fill_to_wire_box_autoadd___record__u8_u8((int,int) apiObj, ffi.Pointer<wire___record__u8_u8> wireObj) {
                _api_fill_to_wire___record__u8_u8(apiObj, wireObj.ref);
            }

void _api_fill_to_wire_box_autoadd_devel_options(DevelOptions apiObj, ffi.Pointer<wire_DevelOptions> wireObj) {
                _api_fill_to_wire_devel_options(apiObj, wireObj.ref);
            }





void _api_fill_to_wire_devel_options(DevelOptions apiObj, wire_DevelOptions wireObj) {
                wireObj.vendor_id = api2wire_u16(apiObj.vendorId);
wireObj.product_id = api2wire_opt_box_autoadd_u16(apiObj.productId);
wireObj.address = api2wire_opt_box_autoadd___record__u8_u8(apiObj.address);
wireObj.endpoint_address = api2wire_opt_box_autoadd_u8(apiObj.endpointAddress);
wireObj.interface_number = api2wire_opt_box_autoadd_u8(apiObj.interfaceNumber);
            }














}

// Section: FFI wire bindings

class wire___record__u8_u8 extends ffi.Struct {
            @ffi.Uint8()
            external int field0;

            @ffi.Uint8()
            external int field1;
        }

class wire_DevelOptions extends ffi.Struct {
            @ffi.Uint16()
            external int vendor_id;

            external ffi.Pointer<ffi.Uint16> product_id;

            external ffi.Pointer<wire___record__u8_u8> address;

            external ffi.Pointer<ffi.Uint8> endpoint_address;

            external ffi.Pointer<ffi.Uint8> interface_number;
        }

class wire_uint_8_list extends ffi.Struct {
            external ffi.Pointer<ffi.Uint8> ptr;

            @ffi.Int32()
            external int len;
        }

typedef _c_init_frb_dart_api_dl = ffi.Int8 Function(ffi.Pointer<ffi.Void>);
typedef _dart_init_frb_dart_api_dl = int Function(ffi.Pointer<ffi.Void>);
typedef _c_wire_supported_layouts = ffi.Void Function(ffi.Int64);
typedef _dart_wire_supported_layouts = void Function(int);
typedef _c_wire_example_config = ffi.Void Function(ffi.Int64);
typedef _dart_wire_example_config = void Function(int);
typedef _c_wire_validate_config_yaml = ffi.Void Function(
  ffi.Int64,
  ffi.Pointer<wire_uint_8_list>,
);
typedef _dart_wire_validate_config_yaml = void Function(
  int,
  ffi.Pointer<wire_uint_8_list>,
);
typedef _c_wire_upload_config_yaml = ffi.Void Function(
  ffi.Int64,
  ffi.Pointer<wire_uint_8_list>,
  ffi.Pointer<wire_DevelOptions>,
);
typedef _dart_wire_upload_config_yaml = void Function(
  int,
  ffi.Pointer<wire_uint_8_list>,
  ffi.Pointer<wire_DevelOptions>,
);
typedef _c_new_box_autoadd_record = ffi.Pointer<wire___record__u8_u8> Function();
typedef _dart_new_box_autoadd_record = ffi.Pointer<wire___record__u8_u8>
    Function();
typedef _c_new_box_autoadd_devel_options = ffi.Pointer<wire_DevelOptions>
    Function();
typedef _dart_new_box_autoadd_devel_options = ffi.Pointer<wire_DevelOptions>
    Function();
typedef _c_new_box_autoadd_u16 = ffi.Pointer<ffi.Uint16> Function(ffi.Uint16);
typedef _dart_new_box_autoadd_u16 = ffi.Pointer<ffi.Uint16> Function(int);
typedef _c_new_box_autoadd_u8 = ffi.Pointer<ffi.Uint8> Function(ffi.Uint8);
typedef _dart_new_box_autoadd_u8 = ffi.Pointer<ffi.Uint8> Function(int);
typedef _c_new_uint_8_list = ffi.Pointer<wire_uint_8_list> Function(ffi.Int32);
typedef _dart_new_uint_8_list = ffi.Pointer<wire_uint_8_list> Function(int);
typedef _c_free_wire_sync_return = ffi.Void Function(
  ffi.Pointer<WireSyncReturn>,
);
typedef _dart_free_wire_sync_return = void Function(
  ffi.Pointer<WireSyncReturn>,
);

class KeyboardApiWire implements FlutterRustBridgeWireBase {
            KeyboardApiWire(ffi.DynamicLibrary lib) : _lib = lib {
                init_frb_dart_api_dl = _lib.lookupFunction<_c_init_frb_dart_api_dl,
        _dart_init_frb_dart_api_dl>('init_frb_dart_api_dl');
dartApi = DartApiDl(init_frb_dart_api_dl);
wire_supported_layouts = _lib.lookupFunction<_c_wire_supported_layouts,
        _dart_wire_supported_layouts>('wire_supported_layouts');
wire_example_config = _lib.lookupFunction<_c_wire_example_config,
        _dart_wire_example_config>('wire_example_config');
wire_validate_config_yaml =
        _lib.lookupFunction<_c_wire_validate_config_yaml,
        _dart_wire_validate_config_yaml>('wire_validate_config_yaml');
wire_upload_config_yaml =
        _lib.lookupFunction<_c_wire_upload_config_yaml,
        _dart_wire_upload_config_yaml>('wire_upload_config_yaml');
new_box_autoadd___record__u8_u8_0 =
        _lib.lookupFunction<_c_new_box_autoadd_record,
        _dart_new_box_autoadd_record>('new_box_autoadd___record__u8_u8_0');
new_box_autoadd_devel_options_0 =
        _lib.lookupFunction<_c_new_box_autoadd_devel_options,
        _dart_new_box_autoadd_devel_options>('new_box_autoadd_devel_options_0');
new_box_autoadd_u16_0 = _lib.lookupFunction<_c_new_box_autoadd_u16,
        _dart_new_box_autoadd_u16>('new_box_autoadd_u16_0');
new_box_autoadd_u8_0 = _lib.lookupFunction<_c_new_box_autoadd_u8,
        _dart_new_box_autoadd_u8>('new_box_autoadd_u8_0');
new_uint_8_list_0 = _lib.lookupFunction<_c_new_uint_8_list,
        _dart_new_uint_8_list>('new_uint_8_list_0');
free_WireSyncReturn = _lib.lookupFunction<_c_free_wire_sync_return,
        _dart_free_wire_sync_return>('free_WireSyncReturn');
            }

            final ffi.DynamicLibrary _lib;

            @internal
            late final DartApiDl dartApi;

            late final _dart_init_frb_dart_api_dl init_frb_dart_api_dl;

            late final void Function(int) wire_supported_layouts;

            late final void Function(int) wire_example_config;

            late final void Function(
              int,
              ffi.Pointer<wire_uint_8_list>,
            ) wire_validate_config_yaml;

            late final void Function(
              int,
              ffi.Pointer<wire_uint_8_list>,
              ffi.Pointer<wire_DevelOptions>,
            ) wire_upload_config_yaml;

            late final ffi.Pointer<wire___record__u8_u8> Function()
                new_box_autoadd___record__u8_u8_0;

            late final ffi.Pointer<wire_DevelOptions> Function()
                new_box_autoadd_devel_options_0;

            late final ffi.Pointer<ffi.Uint16> Function(int) new_box_autoadd_u16_0;

            late final ffi.Pointer<ffi.Uint8> Function(int) new_box_autoadd_u8_0;

            late final ffi.Pointer<wire_uint_8_list> Function(int) new_uint_8_list_0;

            late final void Function(ffi.Pointer<WireSyncReturn>) free_WireSyncReturn;
        }
